package com.example.mapper;

import com.example.model.TOrderManage;


import com.example.model.TOrderManageExample;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface TOrderManageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_order_manage
     *
     * @mbg.generated Mon Jun 10 13:58:15 ICT 2024
     */
    long countByExample(TOrderManageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_order_manage
     *
     * @mbg.generated Mon Jun 10 13:58:15 ICT 2024
     */
    int deleteByExample(TOrderManageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_order_manage
     *
     * @mbg.generated Mon Jun 10 13:58:15 ICT 2024
     */
    int insert(TOrderManage row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_order_manage
     *
     * @mbg.generated Mon Jun 10 13:58:15 ICT 2024
     */
    int insertSelective(TOrderManage row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_order_manage
     *
     * @mbg.generated Mon Jun 10 13:58:15 ICT 2024
     */
    List<TOrderManage> selectByExample(TOrderManageExample example);
    List<TOrderManage> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_order_manage
     *
     * @mbg.generated Mon Jun 10 13:58:15 ICT 2024
     */
    int updateByExampleSelective(@Param("row") TOrderManage row, @Param("example") TOrderManageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_order_manage
     *
     * @mbg.generated Mon Jun 10 13:58:15 ICT 2024
     */
    int updateByExample(@Param("row") TOrderManage row, @Param("example") TOrderManageExample example);
}